language: java
jdk:
- oraclejdk8
services:
  - docker
install: true
script:
 - mvn clean install
after_success:
  - docker login -u="ashraf1abdelrasool" -p="01120266849";
  - docker push ashraf1abdelrasool/torrentclient;